Update sleep.yml

diff --git a/.github/workflows/sleep.yml b/.github/workflows/sleep.yml
--- a/.github/workflows/sleep.yml
+++ b/.github/workflows/sleep.yml
@@ -34,7 +34,13 @@ jobs:
         run: sleep 30s
         shell: bash
 
-      # Intentionally fail this step
-      - name: Fail status check
-        run: exit 1
+      - name: Check file for 'fail'
+        run: |
+          if grep -q 'fail' ./aa; then
+            echo "File contains 'fail'"
+            exit 1
+          else
+            echo "File does not contain 'fail'"
+            exit 0
+          fi
         shell: bash
